### ISSUE TITLE
What is the real purpose of this plug-in?

### ISSUE THREAD

**Issue by bau720123** [jeff-french/newrelic-cordova#3]
hi @jeff-french 
What is the real purpose of this plug-in?
I can't understand~

**Comment by uipoet** [comment]
Installing New Relic manually is complicated. Not only does this plugin make it simple, it makes it possible to automate the installation of New Relic into any Cordova project.

**Comment by b0jan** [comment]
What informations can i obtain later with NR? Since this is integration of native iOS plugin, i won't see any JS stuff?

**Comment by uipoet** [comment]
[RTM](http://newrelic.com/solutions/mobile-application-management)
