### ISSUE TITLE
Phonegap Build

### ISSUE THREAD

**Issue by jabajoo** [jeff-french/newrelic-cordova#4]
Hi jeff,

I have added your plugin to my phonegap app for ios. unfortunately it is not reporting anything to new relic. I checked the package created by phonegap build it seems that it didn't add anything to the project from your plugin. is there an example that you could provide with a more clear instructions?

**Comment by jeff-french** [comment]
Hey @jabajoo, sorry for the super late (and probably no longer helpful) response. @Terekhov is correct that I had the wrong command in the README. It's been updated now. Sorry about that!
